---
ruby_version:    2.2.3
nvm_version:     v0.26.1
node_version:    v0.12.7
phpunit_version: ~4.8

ruby_build_version:   v20150818
default_gems_version: ead67889c91c53ad967f85f5a89d986fdb98f6fb
rbenv_vars_version:   v1.2.0
gem_rehash_version:   v1.0.0
binstubs_version:     v1.4

nvm_root:   /usr/local/nvm
rbenv_root: /usr/local/rbenv

ansible_python_interpreter: /usr/bin/python2

# Some useful paths on the local file system
# Realpath will take a relative path and expand it from where Ansible is being run
#   (as opposed to being relative to what task/playbook it's referenced from)
site_var_dir:    "{{ 'ansible/site_vars' | realpath }}"
storage_dir:     "{{ 'ansible/storage'   | realpath }}"
local_sites_dir: "{{ 'sites'             | realpath }}"
