---
- name: Install Rbenv
  apt: package=rbenv state=present
  sudo: yes

- name: Install Readline Headers
  apt: package=libreadline-dev state=present
  sudo: yes

- name: Give Console User Ownership of Rbenv
  file:
    path: "{{ rbenv_root }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: 0755
  sudo: yes

- name: Install Rbenv Plugins
  git:
    repo: https://github.com/sstephenson/{{ item.name }}.git
    dest: "{{ rbenv_root }}/plugins/{{ item.name }}/"
    version: "{{ item.version | default(omit) }}"
  notify: Rehash Rbenv
  with_items:
    - { name: ruby-build,         version: "{{ ruby_build_version }}" }
    - { name: rbenv-vars,         version: "{{ rbenv_vars_version }}" }
    - { name: rbenv-gem-rehash,   version: "{{ gem_rehash_version }}" }
    - { name: rbenv-default-gems, version: "{{ default_gems_version }}" }

- name: Install Binstubs
  git:
    repo: https://github.com/ianheggie/rbenv-binstubs.git
    dest: "{{ rbenv_root }}/plugins/rbenv-binstubs/"
    version: "{{ binstubs_version }}"
  notify: Rehash Rbenv

- name: Set Default Gems
  copy: src=default-gems dest={{ rbenv_root }}/default-gems

- name: Install
  command: rbenv install {{ ruby_version }} creates={{ rbenv_root }}/versions/{{ ruby_version }}
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
    RUBY_BUILD_CACHE_PATH: "{{ rbenv_root }}/cache"

- name: Add Rbenv to Profile
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh
  sudo: yes
