---
- name: Initialize Production Server
  hosts: production
  remote_user: root

  vars_prompt:
    - name:    ansible_sudo_pass # When Ansible 2 comes out, convert this to use password_hash filter, confirm not empty
      prompt:  Sudo Password
      private: yes
      confirm: yes
    - name:    mysql_pass
      prompt:  MySQL Password
      private: yes
      confirm: yes
    - name:    admin_email
      prompt:  eMail Address for Notifications
      private: no

  vars:
    console_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: Production server must be Ubuntu
      assert:
        that: ansible_distribution == "Ubuntu"
    - name: Production server must be Trusty Tahr or later
      assert:
        that: ansible_distribution_version | version_compare("14.04", ">=")
    - name: Sudo password cannot be empty
      assert:
        that: ansible_sudo_pass != ''
    - name: MySQL password cannot be empty
      assert:
        that: mysql_pass != ''

  roles:
    - Production
    - Common
    - PHP
    - MySQL/Install
