---
- name: Create Database
  postgresql_db:
    name:           "{{ db_name }}"
    login_user:     "{{ postgres_admin | default('postgres') }}"
    login_password: "{{ postgres_pass  | default(omit) }}"
    owner:          "{{ new_postgres_user | default(postgres_admin) }}"
    state:          present

- name: Revoke Connect Privileges
  postgresql_privs:
    database:       "{{ db_name }}"
    login_user:     "{{ postgres_admin | default('postgres') }}"
    login_password: "{{ postgres_pass  | default(omit) }}"
    priv:           CONNECT
    role:           PUBLIC
    state:          absent
    type:           database
