---
- name: Create MongoDB Administrator
  hosts: vagrant
  remote_user: vagrant

  vars:
    mongodb_roles: root,backup,restore
  vars_prompt:
    - name:    new_mongodb_user
      prompt:  New MongoDB Admin
      private: no
    - name:    new_mongodb_pass
      prompt:  New Admin Password
      private: yes
      confirm: yes

  pre_tasks:
    - name: Password cannot be blank
      assert:
        that: new_mongodb_pass != ''

  roles:
    - MongoDB/Install
    - MongoDB/Manage
