---
- name: Create Composer Directory
  file: path={{ ansible_user_dir }}/.composer state=directory

- name: Install PHPUnit
  composer:
    command: require
    arguments: "phpunit/phpunit={{ phpunit_version }}"
    working_dir: "{{ ansible_user_dir }}/.composer/"
    no_dev: no
    prefer_dist: yes
    optimize_autoloader: no
