---
- name: Create Database
  mysql_db:
    name:           "{{ db_name }}"
    login_user:     "{{ mysql_admin }}"
    login_password: "{{ mysql_pass }}"
    collation:      utf8_general_ci
    state:          present
  when: db_name is defined

- name: Create User
  mysql_user:
    name:           "{{ new_mysql_user }}"
    password:       "{{ new_mysql_pass }}"
    login_user:     "{{ mysql_admin }}"
    login_password: "{{ mysql_pass }}"
    priv:           "{{ mysql_user_priv }}"
    state:          present
