---
- name: Create Administrator
  postgresql_user:
    name:            "{{ postgres_admin }}"
    password:        "{{ postgres_pass }}"
    encrypted:       yes
    state:           present
    role_attr_flags: SUPERUSER
  sudo: yes
  sudo_user: postgres

- name: Disable Login for postres User
  postgresql_user:
    name:            postgres
    role_attr_flags: NOLOGIN
  sudo: yes
  sudo_user: postgres

- name: Require Password Authentication
  lineinfile:
    name: /etc/postgresql/9.3/main/pg_hba.conf
    regexp: (local\s+all\s+{{ item }}\s+)peer
    line: \1md5
    state: present
    backrefs: yes
  with_items:
    - postgres
    - all
  sudo: yes
  notify: Restart PostgreSQL
