---
- name: Create HipHop VM Site
  hosts: production

  vars_prompt:
    - name:    ansible_sudo_pass
      prompt:  Sudo Password
      private: yes
    - name:    domain
      prompt:  Domain Name (e.g. codeup.com)
      private: no

  pre_tasks:
    - name: Clean domain name
      set_fact: "domain={{ domain | trim | lower }}"

    - name: Domains cannot have spaces
      assert:
        that: not domain | search("\s")

  roles:
    - HHVM
    - Git-Hook
