---
- name: Create Site Directory
  file:
    path:  "{{ www_home }}/{{ domain }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: www-data
    mode:  03755
  register: dir_create_result
  failed_when: >
    dir_create_result.state != "directory" or
    (dir_create_result.msg is defined and dir_create_result.msg != "chown failed")
  sudo: yes

- name: Create Public Directory
  file:
    path:  "{{ www_home }}/{{ domain }}/public"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: www-data
    mode:  03755
  register: dir_create_result
  failed_when: >
    dir_create_result.state != "directory" or
    (dir_create_result.msg is defined and dir_create_result.msg != "chown failed")
  sudo: yes

- name: Copy Site Config
  template:
    src:   site.conf.j2
    dest:  /etc/nginx/sites-available/{{ domain }}
    owner: "{{ ansible_ssh_user }}"
    group: www-data
    mode:  0640
  sudo: yes
  notify: Restart Nginx

- name: Activate Site
  file:
    src:   /etc/nginx/sites-available/{{ domain }}
    dest:  /etc/nginx/sites-enabled/{{ domain }}
    state: link
  sudo: yes
  notify: Restart Nginx

- name: Create Site Log Directory
  file:
    path:  /var/log/nginx/{{ domain }}
    state: directory
    owner: www-data
    group: www-data
    mode:  0755
  sudo: yes
