---
- name: Create User
  mongodb_user:
    name:           "{{ new_mongodb_user}}"
    password:       "{{ new_mongodb_pass }}"
    login_user:     "{{ mongodb_admin }}"
    login_password: "{{ mongodb_pass }}"
    database:       "{{ db_name | default('admin') }}"
    state:          present
    roles:          "{{ mongodb_roles }}"
